sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 666321
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8d2Q77Xvt6hgq4DVS3
    access-key-secret: JdMosdo5b1gcu4w34Ht3lN9xZvfPgM
    bucket-name: one-sky01